# Generated by Django 6.0.1 on 2026-01-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldquest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name_plural': 'Progress'},
        ),
        migrations.AlterModelOptions(
            name='userstats',
            options={'verbose_name_plural': 'User stats'},
        ),
    ]
