# Generated by Django 6.0.1 on 2026-01-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worldquest", "0002_alter_country_options_alter_progress_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="did_you_know",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="question",
            name="insight",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="question",
            name="surprising_fact",
            field=models.TextField(blank=True),
        ),
    ]
