# Generated by Django 6.0.1 on 2026-01-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worldquest", "0003_add_question_extras"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstats",
            name="quiz_points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userstats",
            name="match_points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
