# Generated by Django 6.0.1 on 2026-01-23 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("worldquest", "0004_add_userstats_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendMatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("accepted", "Accepted"), ("declined", "Declined"), ("canceled", "Canceled"), ("completed", "Completed")], default="pending", max_length=16)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("challenger", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matches_sent", to=settings.AUTH_USER_MODEL)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="friend_matches", to="worldquest.country")),
                ("opponent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matches_received", to=settings.AUTH_USER_MODEL)),
                ("winner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="matches_won", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["challenger", "status"], name="worldquest__challenger_7de5c5_idx"),
                    models.Index(fields=["opponent", "status"], name="worldquest__opponent_22d13f_idx"),
                    models.Index(fields=["country", "status"], name="worldquest__country_7f1126_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FriendMatchResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("correct_count", models.PositiveSmallIntegerField(default=0)),
                ("total_questions", models.PositiveSmallIntegerField(default=0)),
                ("score", models.PositiveIntegerField(default=0)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("match", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="results", to="worldquest.friendmatch")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="match_results", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["match", "user"], name="worldquest__match_88df7c_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="friendmatch",
            constraint=models.CheckConstraint(condition=models.Q(("challenger", models.F("opponent")), _negated=True), name="no_self_match"),
        ),
        migrations.AddConstraint(
            model_name="friendmatchresult",
            constraint=models.UniqueConstraint(fields=("match", "user"), name="uniq_match_result_user"),
        ),
    ]
